# docker-compose build
# APP_PORT=3000 docker-compose up -d
# docker-compose down
version: "3"

volumes:
  mongo-data:

services:
    telefunken-nginx:
        build:
            context: nginx
        image: telefunken-nginx
        container_name: telefunken-nginx
        restart: always
        ports:
            - 80:80
        links:
            - telefunken-node-app
        depends_on:
            - telefunken-node-app

    telefunken-node-app:
        build: ./
        image: telefunken-node-app
        container_name: telefunken-node-app
        restart: always
        environment:
            - MONGO_CONN=mongodb://mongodb:27017/
        ports:
            - ${APP_PORT:-3000}:3000
        links:
            - mongodb
        depends_on:
            - mongodb

    # telefunken-go-app:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile.go-app
    #     image: telefunken-go-app
    #     container_name: telefunken-go-app
    #     restart: always
    #     environment:
    #         - MONGO_CONN=mongodb://mongodb:27017/
    #     ports:
    #         - ${GO_APP_PORT:-3080}:3080
    #     links:
    #         - mongodb

    mongodb:
        image: mongo:4
        container_name: mongo
        restart: always
        expose:
            - "27017"
        volumes:
            - mongo-data:/data/db
